### ISSUE TITLE
hasNotch don't work in Iphone 13

### ISSUE THREAD

**Issue by carl0shd** [react-native-device-info/react-native-device-info#1310]
## Summary

|             |     |
| ----------- | --- |
| Version     | react-native-device-info 8.3.2   |
| Affected OS | IOS   |
| OS Version  | IOS 15  |
| Xcode Version  | 13 RC  |
| Device  | Iphone 13 Simulator  |

## Current behavior

I updated the library version but hasNotch function still return false in a Iphone 13 Simulator.

## Expected behavior
Return true in the new iphone 13 lineups.

**Comment by mikehardy** [comment]
Yep - examine #1309 releasing now!

**Comment by NileshRathore** [comment]
hasNotch still returning false in an iPhone 13 & 13 pro.

**Comment by carl0shd** [comment]
Hi, you are using the latest versions of this library? This bug was fixed
months ago.

**Comment by AhmedAbuelenin** [comment]
@mikehardy
I updated the lib to version 10.3.0 and still get false when call hasNotch in simulator 16.1 iphone 14. 
using react native 0.70.6
xcode 14.1

Any help is appreciated.

**Comment by seco35** [comment]
Experiencing same behavior on iPhone 14 (sim) with version 10.3.0.

**Comment by omprakash8080** [comment]
> Experiencing same behavior on iPhone 14 (sim) with version 10.3.0.

Trying removing and installing this library again.. run npx pod-install
